<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class io_clifor_gen extends Model
{
    use HasFactory;
    protected $fillable=[
        'CHIAVE','COD_DITTA','TIPO_CLIFOR','COD_CLIFOR','RAG_SOC','INDIRIZZO','PARTITA_IVA','CODICE_FISCALE','TELEFONO1','TELEFONO2','FAX','CELLULARE','EMAIL','INTERNET','CAP','CITTA','PROVINCIA','LATITUDINE','LONGITUDINE','COD_CLASSE_SCONTO','FLG_MOD_NEL_DISP','FLG_DEPERIBILITA','COD_CAT_EXTRA_SCONTO','COD_SVILUPPO','NAZIONE','PAGAMENTO','BANCA','AGENZIA','LISTINO_ANAGRAFICO','VALUTA','SCONTI_ANAG_PERC','SCONTI_ANAG_IMP','MAGGIORAZIONE_ANAG_PERC','SCONTO_PIEDE','COD_LISTINO','COD_CONDPAG','COD_VALUTA','MACROAREA','DATA_CREAZIONE','AREA','ZONA','MACROCATEGORIA','DATA_ULT_DOC_NO_FT','CATEGORIA','SOTTOCATEGORIA','DATA_ULT_DOC_FT','DATA_ULT_ORDINE','FIDO_AZIENDALE','DES_RAGGR1','DES_RAGGR2','DES_RAGGR3','COD_MACROAREA','COD_AREA','COD_ZONA','COD_MACROCATEGORIA','COD_CATEGORIA','COD_SOTTOCATEGORIA','DAT_ULT_MOD
'
    ];
}
